# Generated by Django 3.2.8 on 2022-10-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username', max_length=64, unique=True)),
                ('firstname', models.CharField(help_text='Firs tname', max_length=64)),
                ('lastname', models.CharField(help_text='Last name', max_length=64)),
                ('email', models.EmailField(blank=True, help_text='User Email', max_length=64, unique=True)),
            ],
        ),
    ]
