# Generated by Django 3.2.8 on 2022-11-01 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20221031_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Note', max_length='1000')),
                ('date_created', models.DateTimeField(default=datetime.datetime.today, help_text='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Is active')),
                ('project', models.OneToOneField(help_text='Project', on_delete=django.db.models.deletion.CASCADE, to='todos.project')),
                ('user', models.OneToOneField(help_text='Author', on_delete=django.db.models.deletion.CASCADE, to='todos.user')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
