# Generated by Django 3.2.8 on 2022-11-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todo_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
