# Generated by Django 3.2.8 on 2022-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_todo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(help_text='Project', on_delete=django.db.models.deletion.CASCADE, to='todos.project'),
        ),
    ]
